### ISSUE TITLE
数据集是否开源？可以提供一下下载链接吗

### ISSUE THREAD

**Issue by LINHYYY** [WH-Wei/SIAT-Lower-Limb-Motion-Dataset-Codes#3]
您好，冒昧打扰您，看过您的论文后想使用数据集进行一些其他分析，但没有找到数据集的链接，是否进行开源了？如果没有进行开源抱歉打扰了。

**Comment by WH-Wei** [comment]
https://doi.org/10.6084/m9.figshare.c.6271164.v1
